name: Notify on push

on:
  push:
    branches:
      - main

jobs:
  notify-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook to External Server
        run: |
          curl -X POST https://6g0xigfvag.execute-api.ap-northeast-1.amazonaws.com
          -H "Content-Type: application/json" \
          -d '{"push": "true", "branch": "main", "commit": "${{ github.sha }}"}'
